#!/usr/bin/env bash

#PBS -W group_list=bhurwitz
#PBS -j oe
#PBS -N extract-fasta
#PBS -o ./out/
#PBS -q qualified
#PBS -l select=1:ncpus=1:mem=6gb
###and the amount of time required to run it
#PBS -l walltime=24:00:00
#PBS -l cput=24:00:00
#PBS -M scottdaniel@email.arizona.edu
#PBS -m bea

echo Started at $(date)

cd $PBS_O_WORKDIR

set -u
source ./config.sh

if [[ ! -d $DATA_DIR ]]; then
    mkdir -p $DATA_DIR
fi

bedtools getfasta -fi $KNFASTA -bed $KNGFF -s | fold -w 60 > $DATA_DIR/dna-of-CDS-from-known-only.fa

echo Done at $(date)
